import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/mebubars/Navbar";
import QueryProviders from "@/contexts/query-provider";
import Footer from "@/components/mebubars/Footer";

export const metadata: Metadata = {
  title: "Tobams Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProviders>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </QueryProviders>
    </html>
  );
}
